### PR TITLE
setVerificationCode & clearVerificationCode func added

### PR DESCRIPTION
**Pull request by 29satnam**
setVerificationCode & clearVerificationCode methods added and made changes as advised by maintainers in the previous PR.

### CODE REVIEW

**Comment by kpavankotesh** [comment]
@29satnam We'll test this and soon merge it. In the mean time you can consider adding these items. Thanks

- [x] Add validation in setCode method to accept only string of length equivalent to number of text fields. 
- [x] Remove the method `clearVerificationCode` and use `clear` method
- [x] Rename the method `setVerificationCode(_ code: String)` to `set(_ code: String)`
- [x] Add the usage of these new methods in ReadMe.md

**Comment by 29satnam** [comment]
> @29satnam We'll test this and soon merge it. In the mean time you can consider adding these items. Thanks
> 
> * [ ]  Add validation in setCode method to accept only string of length equivalent to number of text fields.
> * [x]  Rename the method `clearVerificationCode` to `clear`
> * [ ]  Rename the method `setVerificationCode(_ code: String)` to `set(_ code: String)`
> * [ ]  Add the usage of these new methods in ReadMe.md

There's already a `clear` method in the file.

**Comment by kpavankotesh** [comment]
Okay @29satnam. Then why aren't you using that method and writing a new method instead? If you need some changes in that method, feel free to update it.

**Comment by pavankotesh** [comment]
Implemented in https://github.com/keepworks/KWVerificationCodeView/pull/47

**Pull request closed without merging**
